import type { Metadata } from "next";
// src/app/layout.js
import '@/styles/main.scss';
import Header from '../components/Header';



export const metadata: Metadata = {
  title: "Totee Block",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
